class BibleChapterChanger {
  String getChapter(String chapter) {
    String chap = "";
    switch (chapter) {
      case "창세기":
        return "ge";
      case "출애굽기":
        return "exo";
      case "레위기":
        return "lev";
      case "민수기":
        return "num";
      case "신명기":
        return "deu";
      case "여호수아":
        return "josh";
      case "사사기":
        return "jdgs";
      case "룻기":
        return "ruth";
      case "사무엘상":
        return "1sm";
      case "사무엘하":
        return "2sm";
      case "열왕기상":
        return "1ki";
      case "열왕기하":
        return "2ki";
      case "역대상":
        return "1chr";
      case "역대하":
        return "2chr";
      case "에스라":
        return "ezra";
      case "느헤미야":
        return "neh";
      case "에스더":
        return "est";
      case "욥기":
        return "job";
      case "시편":
        return "psa";
      case "잠언":
        return "prv";
      case "전도서":
        return "eccl";
      case "아가":
        return "ssol";
      case "이사야":
        return "isa";
      case "예레미야":
        return "jer";
      case "예레미야애가":
        return "lam";
      case "에스겔":
        return "eze";
      case "다니엘":
        return "dan";
      case "호세아":
        return "hos";
      case "요엘":
        return "joel";
      case "아모스":
        return "amos";
      case "오바댜":
        return "obad";
      case "요나":
        return "jonah";
      case "미가":
        return "mic";
      case "나훔":
        return "nahum";
      case "하박국":
        return "hab";
      case "스바냐":
        return "zep";
      case "학개":
        return "hag";
      case "스가랴":
        return "zep";
      case "말라기":
        return "mal";
      case "마태복음":
        return "mat";
      case "마가복음":
        return "mark";
      case "누가복음":
        return "luke";
      case "요한복음":
        return "john";
      case "사도행전":
        return "acts";
      case "로마서":
        return "rom";
      case "고린도전서":
        return "1cor";
      case "고린도후서":
        return "2cor";
      case "갈라디아서":
        return "gal";
      case "에베소서":
        return "eph";
      case "빌립보서":
        return "phi";
      case "골로새서":
        return "col";
      case "데살로니가전서":
        return "1th";
      case "데살로니가후서":
        return "2th";
      case "디모데전서":
        return "1tim";
      case "디모데후서":
        return "2tim";
      case "디도서":
        return "titus";
      case "빌레몬서":
        return "phmn";
      case "히브리서":
        return "heb";
      case "야고보서":
        return "jas";
      case "베드로전서":
        return "1pet";
      case "베드로후서":
        return "2pet";
      case "요한일서":
        return "1jn";
      case "요한이서":
        return "2jn";
      case "요한삼서":
        return "3jn";
      case "유다서":
        return "jude";
      case "요한계시록":
        return "rev";
    }
    return chap;
  }
}
